mod.id=asteria_directorate
# 部署目录名（mods/ 下的文件夹名），与 mod.id 解耦，固定为 ASTD 以避免大小写冲突
mod.deployDirName=ASTD
mod.name=Asteria Directorate
mod.author=Hikari_Nova
mod.description=Description
mod.gameVersion=0.98a
mod.plugin=cn.kasuminova.astd.AsteriaDirectoratePlugin
mod.dependencies=lw_lazylib:LazyLib,MagicLib:MagicLib,shaderLib:GraphicsLib,BoxUtil:zz BoxUtil,lunalib:LunaLib

kotlin.daemon.jvmargs=-Xmx4g

decompiler.version=1.9.3
decompiler.maxParallelThreads=2

starsector.gameDir=/mnt/store/Games/Starsector098-linux
starsector.modsDir=/mnt/store/Games/Starsector098-linux/mods
