import type { TooltipBlock, TooltipPreset } from '../model/tooltipPreset';
import { serializeGameTooltipExport } from './gameTooltipExport';

const escapeKotlinString = (value: string): string =>
  value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, '\\n');

const formatBlockLine = (block: TooltipBlock): string => {
  const escapedText = escapeKotlinString(block.text);

  if (block.kind === 'section-heading') {
    return `        tooltip.addSectionHeading("${escapedText}", Misc.getBasePlayerColor(), Misc.getDarkPlayerColor(), Alignment.MID, 8f)`;
  }

  if (block.kind === 'spacer') {
    return `        tooltip.addSpacer(${block.padTop ?? 8}f)`;
  }

  return `        tooltip.addPara("${escapedText}", ${block.padTop ?? 8}f)`;
};

export const formatTooltipKotlinScaffold = (preset: TooltipPreset): string => {
  const blocks = preset.blocks.map(formatBlockLine).join('\n');
  const json = serializeGameTooltipExport(preset)
    .trimEnd()
    .split('\n')
    .map((line) => `     * ${line}`)
    .join('\n');

  return `package data.hullmods

import com.fs.starfarer.api.ui.Alignment
import com.fs.starfarer.api.ui.TooltipMakerAPI
import com.fs.starfarer.api.util.Misc

/*
 * Tooltip style scaffold generated by tools/tooltip-style-editor.
 *
 * This is a wiring sketch, not a final in-game renderer. Port the exported
 * style payload into the real hullmod class and connect the background through
 * ASTDShaderTooltipBackground when the game-side renderer exists.
 *
 * Export payload:
${json}
 */
class ${preset.hullmod.id
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join('')}TooltipScaffold {
    fun addPostDescriptionSection(tooltip: TooltipMakerAPI, width: Float, isForModSpec: Boolean) {
        // TODO: Attach ASTDShaderTooltipBackground with shaderId "${escapeKotlinString(preset.background.shaderId)}".
        tooltip.addPara("${escapeKotlinString(preset.hullmod.displayName)}", 0f)
${blocks}
    }
}
`;
};
